#! /bin/sh
#
# FILE
#	atom_get	--  Fetches an atom from an AtomTorrent atomstore by its Atom-ID
#
# DESCRIPTION
#	Fetches an atom from an AtomTorrent atomstore by its Atom-ID, and saves or displays it.
#
#	If an output filename is provided as the 2nd non-flag argument then the fetched atom
#	will be written to a file of that name.  If the output filename is omitted then the
#	atom will be written to standard output, unless the -s flag ("silent") is given.
#
#	The -v flag provides some feedback on progress, either as "{Atom-ID} {output-file}" pairs
#	or, when no output filename is provided, as a separator containing the Atom-ID so that
#	multiple invocations are separated on stdout.
#
#	Uses the curl commandline utility -- see http://curl.haxx.se/
#	and the wget commandline utility  -- see http://www.gnu.org/software/wget/
#
# AUTHORS
#	Morgaine Dinova <morgaine.dinova@googlemail.com>
#
# LICENSE
#	Public Domain
#

PROG=`basename $0`

pr2()
{
	echo "$*"  1>&2
}

usage()
{
	pr2 "Usage is:  $PROG  [-h] [-v] [-s]  [-H {URL-of-atomstore}]  {Atom-ID}  [{output-file}]"
	exit 1
}

ATOMSTORE_URL="http://localhost:5080/"
DEBUGGING="false"
VERBOSE="false"
SILENT="false"
OUT_BUFFER="/tmp/XXX_${PROG}-output__XX"

while true
do
	case "$1" in
	-h)
		usage
		;;
	-d)
		DEBUGGING="true"
		;;
	-v)
		VERBOSE="true"
		;;
	-s)
		SILENT="true"
		;;
	-H)
		ATOMSTORE_URL="$2"
		shift
		;;
	-*)
		pr2 "$PROG:  bad flag {$1}"
		usage
		;;
	*)
		break
		;;
	esac
	shift
done

recv_file()
{
	ATOM_ID="$1"
	FILE="$2"

	#
	# curl has several bugs which trigger when GET fails:
	# (i)  it doesn't return an error exit status so we can't tell that there is an error with any
	#      certainty (parsing the returned HTML is not distinguishable from that HTML being returned
	#      as a valid atom body).
	# (ii) "curl --fail" does return the error exit status, but it closes its HTTP session uncleanly
	#      and that triggers a bug in the BaseHTTPRequestHandler class library which results in a
	#      very annoying traceback being called during exception handling.
	# Since this isn't easily corrected, I'm not using curl for detecting bad GETs.
	#
	#	curl -s --fail "${ATOMSTORE_URL}/${ATOM_ID}" > "$OUT_BUFFER"
	#
	# Instead I'll use wget.
	#
	# Unfortunately, wget in turn has a problem, in that although it does return the error exit status
	# properly, it doesn't output the body of the response from the web server on GET fail.  So, really
	# ridiculously, I'm using wget to get the error exit status reliably and curl to get the body!!!
	#
	# Yuck, lol !!
	#
	wget -q -O - "${ATOMSTORE_URL}/${ATOM_ID}" > "$OUT_BUFFER"
	if [ "$?" != 0 ]
	then
		curl -s "${ATOMSTORE_URL}/${ATOM_ID}" > "$OUT_BUFFER"
		MSG1=`sed -e '/^<p>Error code [0-9]/!d' -e 's/^<p>Error code //' -e 's/\.$//'  "$OUT_BUFFER"`
		MSG2=`sed -e '/^<p>Message: /!d' -e 's,^.*[/],,' -e 's/\.$//'  "$OUT_BUFFER"`
		REASON="  -- Error code $MSG1, Atom not found"
		#
		# Flaming webbies, returning what should be machine status in HTML.
		# Having to "scrape" error information is just plain ridiculous.
		# And of course this will break as soon as they change text ... :-(
		# Not impressed.
		#
		if [ -n "$FILE" ]
		then
			IDENTIFY=" for file {$FILE}"
		else
			IDENTIFY=""
		fi
		pr2 "$PROG:  FAILED to GET Atom-ID {$ATOM_ID}${IDENTIFY}${REASON}"
		return 1
	fi
	return 0
}

if [ -z "$1" ]
then
	usage
fi

ATOM_ID="$1"
if [ -n "$2" ]
then
	FILE="$2"
	VERBOSE_IDENTIFIER="${ATOM_ID}  ${FILE} :"
else
	FILE=""
	VERBOSE_IDENTIFIER="======================  ${ATOM_ID}  ======================"
fi

$VERBOSE && pr2 "${VERBOSE_IDENTIFIER}"

if recv_file  "$1"  "$FILE"
then
	if [ -n "$FILE" ]
	then
		mv "$OUT_BUFFER"  "$FILE"  2>/dev/null
		if [ "$?" != 0 ]
		then
			pr2 "$PROG:  Fetch of Atom-ID {$ATOM_ID} succeeded but FAILED in write to file {$FILE}"
			return 2
		fi
	elif "$SILENT"
	then
		:
	else
		cat "$OUT_BUFFER"
	fi

	rm -f "$OUT_BUFFER"
fi
